### ISSUE TITLE
Add a toggle that enables/disables GTM.

### ISSUE THREAD

**Issue by perrijs** [phantomstudios/react-gtm#9]
> What is the problem you're trying to solve?

We need to be able to disable GTM site wide, not just control for custom events, in the event that a user rejects cookies.

> What solution would you like to see?

Add a toggle that enables/disables GTM when appropriate.

**Comment by DanRossPhantom** [comment]
Have addressed this in PR https://github.com/phantomstudios/react-gtm/pull/11

**Comment by DanRossPhantom** [comment]
Ah, John's suggestion is, of course, the better one.

**Comment by PauloMFJ** [comment]
#15 and #12 provide two possible solutions. As per discussions with @digitaljohn these still might not be the ideal solution as they require you to pass in tracking ID beyond `_document` level. But for now would address this issue.
